---
title: "Wiltermuth 2011: Replication"
author: "Em reit"
date: "February 26, 2017"
output: html_document
---

```{r}
library(car)
library(psych)
library(tidyverse)
library(tidyr)
library(dplyr)
```


```{r}
#Load in raw data.
setwd("~/Documents/StanfordCoursework/winter2017/MF's/Project/wiltermuth2011/Pilot A")

#Remove the first two header lines from Qualtrics raw file.
all_content = readLines("wiltermuth2011_pilotA.csv")
skip_second = all_content[-1]
skip_third = skip_second[-1]
qualtrics = read.csv(textConnection(skip_third), header = TRUE, stringsAsFactors = FALSE)
```


```{r cheating count}
d <- qualtrics

#Embedded data is set to Condition = self-alone or self-other. These are the two conditions used for analyses.


#cheat_alone and cheat_other are the binary "yes/no" variables about having solved the unsovlable 3rd word.
d$cheat_alone <- as.numeric(d$cheat_alone)
d$cheat_other <- as.numeric(d$cheat_other)

#this combines the cheating measure across conditions for analyses.
d$cheat <- NA
d$cheat[which(d$cheat_alone == 1 | d$cheat_other == 1 )] <- "yes"
d$cheat[which(d$cheat_alone == 2 | d$cheat_other == 2 )] <- "no"
```


```{r frequency of cheating per condition}
cheatfrequency <- d %>% group_by(Condition, cheat) %>% dplyr::summarise(freq=n())
print(cheatfrequency)
```


```{r chi-square test of interest}
#prop <- as.table(matrix(c(alone_yes, alone_no, other_yes, other_no), byrow=T,ncol=2))
#print(prop)
#chisq.test(prop)


#rsa <- lm(cheat ~ Condition, data = d); summary(rsa)